version: '3'
services:
  proxy:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://admin:admin@cluster.0zkqkyk.mongodb.net/?retryWrites=true&w=majority
      - TOKEN_KEY=7014e0105bd8e387ad374ce8b8c542bc2a61cd1f52ade49dfb41bc0c4f12443d
    networks:
      - mynetwork
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - 3000:80
    networks:
      - mynetwork
  ml:
    build: 
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - mynetwork
networks:
  mynetwork: